apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application-02
  namespace: argocd-app-02
spec:
  project: default

  source:
    repoURL: https://github.com/PeteJax123/argo-cd-simple-pod.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd-app-02

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
